version: '3'
services:
   jenkins:
     build: .
     image: jenkins-docker
     restart: always
     container_name: jenkins-docker
     ports:
       - "8965:8080"
     volumes:
       - ./data/jenkins:/var/jenkins_home
       - /var/run/docker.sock:/var/run/docker.sock